# Generated by Django 3.2.3 on 2021-07-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0007_song_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='viewer',
            field=models.IntegerField(default=0),
        ),
    ]
